### ISSUE TITLE
Error: htmlspecialchars() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by soyjonathanespinosa** [spatie/laravel-translation-loader#85]
Hello,

I am trying to use this package, I already installed and create 1 translation in database, I put the trans() function in login blade and is not working, is giving me:

ErrorException (E_ERROR)
htmlspecialchars() expects parameter 1 to be string, array given 
(View: C:\laragon\www\***\resources\views\layouts\app.blade.php) 
(View: C:\laragon\www\***\resources\views\layouts\login.blade.php)

Then, I remove it and still the problem. 

Could you please help me? Thank you

**Comment by freekmurze** [comment]
There's too little information here for us to go on. Could you submit a failing test for us to look at?

**Comment by applyACS** [comment]
It's easy to test
Create a translation file called documents.php in your lang folder for example, with some strings in it
Here's a simple one for documents.php
```
<?php

return [
    'document_type'     => [
        '10' => 'Seller',
        '20' => 'Agent',
    ];
```
Now, if anywhere in your template you try to display a translation using the name of the file, for eg ```{{ __('Documents') }}``` or ```{{ __('documents') }}``` it will give you this error since it returns the translations as an array. This is a bug as it should only return the translation array if you have a dot ```.``` in the translated string.
